### PR TITLE
Update V8 to 9.8.177.4

### PR DESCRIPTION
**Pull request by spahnke**
To do that we need to update the platform toolset to v143/Visual Studio 2022

### CODE REVIEW

**Review by Ablu — APPROVED** [review]

**Comment by Ablu** [comment]
Looks like you need to bump the appveyor config too?

**Comment by spahnke** [comment]
It seems the targeting pack for .NET Framework 4.5 doesn't exist anymore. Even though it's listed in the Appveyor Visual Studio 2022 config [here](https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_vs2022.ps1#L51-L243) it isn't listed at all if I look into my local Visual Studio installer. Should we consider updating to at least 4.7.2? Especially because the earlier .NET Framework versions will not get security updates anymore (https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers)?

**Comment by Ablu** [comment]
> Should we consider updating to at least 4.7.2? Especially because the earlier .NET Framework versions will soon not get security updates anymore (https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers)?

Sounds reasonable to me

**Comment by spahnke** [comment]
I pushed that change for now, but the discussion stays open of course. Aaaand the Windows SDK version is also too old for appveyor...

**Review by oliverbock — APPROVED** [review]

**Pull request merged**
