### PR TITLE
WIP: Added attribute for marking properties as enumerable

### PR DESCRIPTION
**Pull request by OxCoffee**
Here is a suggestion for marking properties as enumerable using attributes for user-defined (CLR) types. Please, give me feedback that it can be achived by the attribute mechanism. There are some pain points for using the other functions like "Object.values" or the "for-in-loop". There is no distinction flag or so on between the normal enum and objects with inherited members. I don't know the the way to distinguish between these situations?

### CODE REVIEW

**Comment by Ablu** [comment]
Hi,

I am a co-worker of @OxCoffee (and @spahnke).

> why not just define a property in C# that returns the names of these particular properties/methods? It does not seem worth making Javascript.Net more complicated for this.

well this change is about adding support for enumerating properties in the standard JavaScript way (using `Object.keys()` and functions alike). If I understand your proposal correctly we would need to add a `.keys()` function / property to our objects for this enumeration and would not be able to use the standard JavaScript features anymore. We are seeking for the opportunity to switch over from the Jurassic engine where we had this feature and need to deal with existing code outside of our control which uses it.

Thus we are highly interested in contributing an solution which allows the use of the standard JavaScript features.

Does that explain the use case a bit better?

Regards,
Erik

**Comment by oliverbock** [comment]
An obvious implementation of Object.keys() for C# objects would enumerate all public properties and methods.  This would make some sense to me, though I do not see it as very useful because people typically use Object.keys() to interrogate dynamic objects, where the keys cannot be known in advance.  Normal C# classes have a fixed set of properties, so there is _generally_ no need for this. 

Without better arguments, I don't support the above change because it will complicate a project that does not anyway get a lot of attention.

However I understand that you are suggesting not that public properties/methods should be enumerated, but that only those marked with a special attribute be included.  This is _more_ complicated and I do not see how this is generally useful.  Please explain your motivation.

**Comment by Ablu** [comment]
> However I understand that you are suggesting not that public properties/methods should be enumerated, but that only those marked with a special attribute be included. This is more complicated and I do not see how this is generally useful. Please explain your motivation.

In our case it would actually probably be fine if all properties/methods are enumerable... We just figured that this would in theory be not backwards-compatible with existing code since now suddenly `Object.keys()` would return values where it would not before... The question is how critical that would be.

> An obvious implementation of Object.keys() for C# objects would enumerate all public properties and methods. This would make some sense to me, though I do not see it as very useful because people typically use Object.keys() to interrogate dynamic objects, where the keys cannot be known in advance. Normal C# classes have a fixed set of properties, so there is generally no need for this.


While this is true for `Object.keys()`, we also frequently deal with code which uses `Object.assign()` which also depends on enumerable properties. And we see `assign()` also being frequently used in cases where the properties are known, but copying them over from one object to another would be rather tedious to do by hand.


So... Would you be fine with an "enumerable by default" solution?

**Comment by oliverbock** [comment]
I'm not worried about the backward compatibility aspect because I think it is unlikely, and I think it is more important that JavaScript.Net be obvious and simple.

Does Object.assign() depend on Object.keys()?  In that case, I guess you would only want _properties_ to be enumerated, because trying to copy _methods_ would cause errors.  You could consider that the methods are part of the class, not the instance, and in JavaScript land would not be returned by Object.keys() because they come from the prototype link.  I would be OK with that.

**Comment by Ablu** [comment]
> Does Object.assign() depend on Object.keys()? In that case, I guess you would only want properties to be enumerated, because trying to copy methods would cause errors. You could consider that the methods are part of the class, not the instance, and in JavaScript land would not be returned by Object.keys() because they come from the prototype link. I would be OK with that.

this sounds good to me as well

**Pull request closed without merging**
